site_name: ICDAR 2021 Competition on Historical Map Segmentation
repo_url: https://github.com/icdar21-mapseg/icdar21-mapseg.github.io
site_description: Official site for the ICDAR 2021 Competition on Historical Map Segmentation. Register, download the dataset and evaluation tools here.
site_author: J. Chazalon; E. Carlinet; Y. Chen; J. Perret; C. Mallet; B. Duménieu; T. Géraud
# google_analytics: ['UA-????????-?', 'icdar21-mapseg.github.io']
theme:
    name: readthedocs
    # collapse_navigation: true
edit_uri: edit/main/docs/
nav:
  - index.md
  - Tasks:
    - tasks/task1.md
    - tasks/task2.md
    - tasks/task3.md
  - Participate:
    - downloads.md
    - registration.md
    - rules.md
  - More information:
    - contact.md
    # - 'Issue Tracker (external)': 'https://github.com/icdar21-mapseg/icdar21-mapseg.github.io/issues'
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
strict: true