site_name: DigiKAR QGIS tutorial
repo_url: https://github.com/digikar-qgis/digikar-qgis.github.io
site_description: The companion site to the QGIS training session for DigiKAR, July 11-12, 2023.
site_author: Bertrand Duménieu
theme:
    name: readthedocs
    # collapse_navigation: true
    custom_dir: theme_customizations
edit_uri: edit/main/docs/
nav:
  - index.md
  - programme.md
  #- Resources:
  #  - downloads.md
    #- '🏆 Score board': score_board.md
    # - registration.md
    # - rules.md
  - More information:
    - contact.md
    # - 'Issue Tracker (external)': 'https://github.com/icdar21-mapseg/icdar21-mapseg.github.io/issues'
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
  - attr_list
  - fontawesome_markdown
strict: false
# new analytics
# google_analytics: ['G-HSMK67B4JN', 'icdar21-mapseg.github.io']
extra_css:
  - 'stylesheets/extra.css'